### ISSUE TITLE
GA Support?

### ISSUE THREAD

**Issue by ratson** [pushtell/react-ab-test#1]
I see https://github.com/pushtell/react-ab-test/commit/fbd4c11e0f5b834caccca7fb047bb0c59c6fb035 moved GA related code to a branch.

Is there any limitations about GA for integration?

**Comment by wehriam** [comment]
There are no limitations on GA. That branch was formed around [Content Experiments](https://support.google.com/analytics/answer/1745147?hl=en) rather than core event tracking. It will eventually use the Content Experiments API to choose the version to display, and report directly into the Content Experiment results. Unfortunately that will require server side work that extends beyond this  project's current scope.

To [record events using analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) you could do something like:

```js
emitter.addPlayListener(function(experimentName, variantName){
  ga('send', {
    hitType: 'event',
    eventCategory: experimentName,
    eventAction: 'play',
    eventLabel: variantName
   });
});
```

If you're tracking wins you might add: 

```js
emitter.addWinListener(function(experimentName, variantName){
  ga('send', {
    hitType: 'event',
    eventCategory: experimentName,
    eventAction: 'win',
    eventLabel: variantName
   });
});
```
